//============================================================================
//
//   SSSS    tt          lll  lll
//  SS  SS   tt           ll   ll
//  SS     tttttt  eeee   ll   ll   aaaa
//   SSSS    tt   ee  ee  ll   ll      aa
//      SS   tt   eeeeee  ll   ll   aaaaa  --  "An Atari 2600 VCS Emulator"
//  SS  SS   tt   ee      ll   ll  aa  aa
//   SSSS     ttt  eeeee llll llll  aaaaa
//
// Copyright (c) 1995-2026 by Bradford W. Mott, Stephen Anthony
// and the Stella Team
//
// See the file "License.txt" for information on usage and redistribution of
// this file, and for a DISCLAIMER OF ALL WARRANTIES.
//
//   Based on code from ScummVM - Scumm Interpreter
//   Copyright (C) 2002-2004 The ScummVM project
//============================================================================

#ifndef GUI_OBJECT_HXX
#define GUI_OBJECT_HXX

class Dialog;
class DialogContainer;
class Widget;
class OSystem;

#include "BitmaskEnum.hxx"
#include "Command.hxx"
#include "Vec.hxx"

// Non-owning list of widgets (focus lists, button groups, ...)
using WidgetArray = vector<Widget*>;
// Owning list of widgets; each GuiObject owns the widgets created with it
// as their boss
using WidgetList = vector<unique_ptr<Widget>>;

// Bits of GuiObject::_flags, controlling appearance/behavior.  A free enum
// (not nested in GuiObject) because its Bitmask::is_enum_v specialization
// must be visible before GuiObject's inline members use it, and those are
// compiled as if written immediately after the class -- too late for a
// specialization declared after the closing brace.
enum class GuiObjectFlag: uInt16 {
  None         = 0,
  Enabled      = 1 << 0,
  Invisible    = 1 << 1,
  Hilited      = 1 << 2,
  Border       = 1 << 3,
  ClearBG      = 1 << 4,
  TrackMouse   = 1 << 5,
  RetainFocus  = 1 << 6,
  WantsTab     = 1 << 7,
  WantsRawData = 1 << 8,
  NoBG         = 1 << 9,
  MouseFocus   = 1 << 10
};
template<> inline constexpr bool Bitmask::is_enum_v<GuiObjectFlag> = true;

/**
  This is the base class for all GUI objects/widgets.

  @author  Stephen Anthony
*/
class GuiObject : public CommandReceiver
{
  friend class Widget;
  friend class DialogContainer;

  public:
    // Re-exposed as a member so callers keep writing GuiObject::Flag / Widget::Flag
    using Flag = GuiObjectFlag;

  public:
    // The commands generated by various widgets
    struct Cmd {
      static constexpr GuiCmd::Code
        OK          = GuiCmd::of("GuiObject.OK"),
        Close       = GuiCmd::of("GuiObject.Close"),
        Next        = GuiCmd::of("GuiObject.Next"),
        Prev        = GuiCmd::of("GuiObject.Prev"),
        Defaults    = GuiCmd::of("GuiObject.Defaults"),
        SetPosition = GuiCmd::of("GuiObject.SetPosition");
    };

  public:
    /** 'w'/'h' are the initial size; most subclasses resize themselves in layout() */
    GuiObject(OSystem& osystem, DialogContainer& parent, Dialog& dialog,
              int w, int h);

    /** Out-of-line: Widget must be complete where _children (vector<unique_ptr<Widget>>) is destroyed */
    ~GuiObject() override;

    /** The parent system, dialog stack, and owning dialog */
    OSystem& instance() const       { return myOSystem; }
    DialogContainer& parent() const { return myParent;  }
    Dialog& dialog() const          { return myDialog;  }

    /** Position/size in screen coordinates; a Dialog's are its own, a Widget's come from its boss */
    virtual int getAbsX() const     { return _x; }
    virtual int getAbsY() const     { return _y; }
    /** Where this object's own children are placed, relative to the screen */
    virtual int getChildX() const   { return getAbsX(); }
    virtual int getChildY() const   { return getAbsY(); }
    virtual int getWidth() const    { return _w; }
    virtual int getHeight() const   { return _h; }

    virtual void setWidth(int w)    { _w = w; }
    virtual void setHeight(int h)   { _h = h; }

    /** Whether this object is currently shown (and not hidden by an ancestor) */
    virtual bool isVisible() const = 0;

    virtual void draw() = 0;
    /** Marks this object as needing to be redrawn */
    virtual void setDirty() = 0;
    /** Marks this object and everything drawn above it as needing to be redrawn */
    virtual void setDirtyChain() = 0;
    void clearDirty() { _dirty = false; }
    void clearDirtyChain() { _dirtyChain = false; }
    bool isDirty() const { return _dirty; }
    bool isChainDirty() const { return _dirtyChain; }

    // The GUI indicates if its underlying surface needs to be redrawn
    //  and then re-rendered
    virtual bool needsRedraw() { return isDirty() || isChainDirty(); }

    /** Advance any time-based state (e.g. cursor blink, tooltip delay) */
    virtual void tick() = 0;

    /**
      Re-read all state derived from the font, which has been changed in place
      (see OSystem::refreshFonts).  What that means differs by kind, which is
      why it lives here: a Widget re-reads its cached metrics, while a Dialog
      does that for its whole widget tree and then re-runs its layout.
    */
    virtual void refreshFont() = 0;

    /** Sets the given Flag bits, marking this object dirty if they changed */
    void setFlags(Flag flags, bool updateDirty = true)
    {
      const Flag oldFlags = _flags;

      _flags |= flags;
      if(updateDirty && oldFlags != _flags)
        setDirty();
    }
    /** Clears the given Flag bits, marking this object dirty if they changed */
    void clearFlags(Flag flags, bool updateDirty = true)
    {
      const Flag oldFlags = _flags;

      _flags &= ~flags;
      if(updateDirty && oldFlags != _flags)
        setDirty();
    }
    /** Whether any bit in 'mask' is currently set in _flags */
    bool hasFlag(Flag mask) const { return Bitmask::Enum{_flags}.any_of(mask); }

    /** The Flag::Border/Flag::ClearBG/Flag::NoBG bits, queried individually */
    bool hasBorder() const { return hasFlag(Flag::Border); }
    bool clearsBackground() const { return hasFlag(Flag::ClearBG); }
    bool hasBackground() const { return !hasFlag(Flag::NoBG); }

    /** Add given widget(s) to the focus list */
    virtual void addFocusWidget(Widget* w) = 0;
    /** Add every widget in 'list' to the focus list; returns the new focus list size */
    virtual int addToFocusList(const WidgetArray& list) = 0;

    /** Return focus list for this object */
    WidgetArray& getFocusList() { return _focusList; }

    /** Redraw the focus list */
    virtual void redrawFocus() { }

    /** Special characters for menues */
    const string ELLIPSIS = "\x1d";
    const string DEGREE = "\x1c";

  protected:
    /** Gives up the input focus this object currently holds */
    virtual void releaseFocus() = 0;
    /** Draws this object and everything drawn above it */
    virtual void drawChain() = 0;

    /** URL of this object's context-help page, if any */
    virtual string getHelpURL() const = 0;
    /** Whether getHelpURL() has anything to offer */
    virtual bool hasHelp() const = 0;

  private:
    // Parent system, dialog stack, and owning dialog
    OSystem&         myOSystem;
    DialogContainer& myParent;
    Dialog&          myDialog;

  protected:
    // Position and size in screen coordinates
    int  _x{0}, _y{0}, _w{0}, _h{0};
    bool _dirty{false};
    bool _dirtyChain{false};
    // Flag bits currently set
    Flag _flags{Flag::None};

    // The child widgets owned by this object; a Widget appends itself to its
    // boss's list at construction (see the Widget constructor)
    WidgetList  _children;
    // Widgets that can take the input focus, in tab order
    WidgetArray _focusList;

  private:
    // Following constructors and assignment operators not supported
    GuiObject() = delete;
    GuiObject(const GuiObject&) = delete;
    GuiObject(GuiObject&&) = delete;
    GuiObject& operator=(const GuiObject&) = delete;
    GuiObject& operator=(GuiObject&&) = delete;
};

#endif  // GUI_OBJECT_HXX
