#!/usr/local/bin/perl -w
use strict;
use File::Temp qw(tempfile);
my $file = shift;
my $match = @ARGV ? shift : '^f';
open(my $dat,$file) || die "Cannot open $file:$!";
my @labels;
my $sym;
my $ymin = 75;
my $ymax = 95;
SCAN:
while (<$dat>)
 {
  if (s/^\s*#\s*//)
   {
    s/\s+$//;
    my @lab = split(/\s+/,$_); 
    push(@labels,[@lab]);
    # warn "Possible labels:@lab\n";
    $sym = $lab[0] if @lab == 1;
   }
  else
   {
    # warn "Data:$_";
    s/^\s+//;
    s/\s+$//;
    my @data = split(/\s+/,$_);
    foreach my $lab (@labels)
     {
      if (@$lab == @data)
       {
        @labels = @$lab;
	last SCAN;
       }  
     } 
    die "$file:$.:No labels match @data\n"; 
   } 
 }
 
my ($fh,$path) = tempfile();
 
my $lx = 0; 
my $x  = 0;
my $yp = $ymin;
while (<$dat>)
 {
  if (/^\s*#/)
   {
    if (/^\s*#\s+(\S+)\s*$/ && $1 ne $sym)
     {
      my $xp = ($x+$lx)/2;
      printf $fh qq[set label "$sym" at %g,%g center rotate \n],$xp,$yp;
      $lx = $x;
      $sym = $1;
      $yp += 5;
      $yp = $ymin if $yp > $ymax;
     }
   }
  else
   {
    $x++;
   }   
 } 
 
warn "Labels: @labels\n";

print $fh "set data style line\n";
my $i = 1;
my $sep = 'plot';
while (@labels)
 {
  my $lab = shift(@labels);
  if ($lab =~ /$match/o)
   {
    print $fh qq[$sep "$file" using 0:$i title "$lab"];
    $sep = ",\\\n     ";  
   } 
  $i++;
 }
print $fh "\n";
close($fh);
system('gnuplot',-title => "$file /$match/", '-persist',$path);
