#!/usr/bin/env python3
"""Bake the FujiNet CONFIG client image into the C++ FujiConfigROM.hxx header.

The 2600 has no disk and no boot loader: the console runs whatever the
cartridge serves at $FFFC, so on real hardware CONFIG is the RP2040's own boot
ROM, memcpy'd out of flash by fuji_config_boot() before the bus comes up.
Stella has no flash, so it carries the image the same way it carries DefProps
-- generated by hand, committed, compiled in.  That keeps the build free of
any dependency on the fujinet-config tree or on Macroassembler AS, neither of
which CI or a release builder has.

This is the same job as fujinet-config/atari-2600/tools/mkromh.py, which bakes
the identical image into the cartridge firmware; the only differences are the
output language and the claim check below.

Usage: create_fujiconfigrom.py [INPUT config.bin] [OUTPUT header]
  default input:  $FUJINET_CONFIG/atari-2600/build/config.bin
                  ($FUJINET_CONFIG defaults to ~/Workspace/fujinet-config)
  default output: src/emucore/fujinet/FujiConfigROM.hxx
"""

import os
import sys
from pathlib import Path

USAGE = __doc__

# The shape CartDetector::isProbablyFUJI() tests for.  Kept in step with
# src/emucore/CartDetector.cxx by hand: an image that fails there would be
# baked in, boot, and serve a dead mailbox, which is a much worse error than
# refusing to generate.
BANK_SIZE = 2048
CLAIM_OFFSET = 0x710            # FN_R_CLAIM - $1800
CLAIM = b"FUJI"
MAX_BANKS = 113                 # FN_APP_MAX_PAGES banks, plus the fixed half

HEADER = """\
//============================================================================
//
//   SSSS    tt          lll  lll
//  SS  SS   tt           ll   ll
//  SS     tttttt  eeee   ll   ll   aaaa
//   SSSS    tt   ee  ee  ll   ll      aa
//      SS   tt   eeeeee  ll   ll   aaaaa  --  "An Atari 2600 VCS Emulator"
//  SS  SS   tt   ee      ll   ll  aa  aa
//   SSSS     ttt  eeeee llll llll  aaaaa
//
// Copyright (c) 1995-2026 by Bradford W. Mott, Stephen Anthony
// and the Stella Team
//
// See the file "License.txt" for information on usage and redistribution of
// this file, and for a DISCLAIMER OF ALL WARRANTIES.
//============================================================================

#ifndef FUJI_CONFIG_ROM_HXX
#define FUJI_CONFIG_ROM_HXX

#include "bspf.hxx"

/**
  The FujiNet CONFIG client -- host slots, browser, WiFi setup, copy and boot.

  This code is generated using the 'create_fujiconfigrom.py' script, located
  in the src/tools directory.  All client changes should be made in the
  fujinet-config project, and then this file should be regenerated and the
  application recompiled.

  It is the cartridge's boot ROM, not a game: at power-up a FujiNet cartridge
  has no network and nothing to load a client from, so the client has to be
  the image it already holds.  The RP2040 firmware bakes this same image into
  flash (fujiboot.c); this header is Stella's flash.
*/

namespace FujiNet {

"""


def _default_input():
    root = os.environ.get("FUJINET_CONFIG",
                          str(Path.home() / "Workspace" / "fujinet-config"))
    return str(Path(root) / "atari-2600" / "build" / "config.bin")


def _default_output():
    # Saves having to type the path every single time, run from either the
    # source root or src/tools (as create_props.py does)
    primary = "src/emucore/fujinet/FujiConfigROM.hxx"
    return primary if Path(primary).parent.is_dir() \
        else "../emucore/fujinet/FujiConfigROM.hxx"


def check_claim(image, path):
    """Refuse anything CartDetector::isProbablyFUJI() would not recognise."""
    size = len(image)
    if size < 2 * BANK_SIZE or size > MAX_BANKS * BANK_SIZE:
        raise SystemExit(f"{path}: {size} bytes is not 2..{MAX_BANKS} banks")
    if size % BANK_SIZE:
        raise SystemExit(f"{path}: {size} bytes is not a multiple of 2K")

    # The fixed half is the LAST 2K whatever the image's size
    at = size - BANK_SIZE + CLAIM_OFFSET
    if image[at:at + len(CLAIM)] != CLAIM:
        raise SystemExit(f"{path}: no 'FUJI' claim at offset {at:#x} -- "
                         "not a FujiNet client image")


def main(argv):
    if argv and argv[0] in ("-help", "--help", "-h"):
        print(USAGE)
        return 0
    if len(argv) > 2:
        print(USAGE)
        return 1

    infile = argv[0] if len(argv) >= 1 else _default_input()
    outfile = argv[1] if len(argv) >= 2 else _default_output()

    try:
        image = Path(infile).read_bytes()
    except OSError as e:
        raise SystemExit(f"create_fujiconfigrom.py: {e}") from e

    check_claim(image, infile)

    rows = [
        "  " + " ".join(f"0x{b:02X}," for b in image[i:i + 16])
        for i in range(0, len(image), 16)
    ]

    with open(outfile, "w", encoding="utf-8") as out:
        out.write(HEADER)
        out.write(f"inline constexpr std::array<uInt8, {len(image)}> "
                  f"CONFIG_ROM = {{\n")
        out.write("\n".join(rows).rstrip(","))
        out.write("\n};\n\n")
        out.write("}  // namespace FujiNet\n\n")
        out.write("#endif  // FUJI_CONFIG_ROM_HXX\n")

    print(f"{outfile}: {len(image)} bytes, "
          f"{len(image) // BANK_SIZE} banks from {infile}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
